apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    tier: frontend
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx
      tier: frontend      
  template:
    metadata:
      labels:
        app: my-nginx
        tier: frontend
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        